org.gradle.jvmargs=-Xmx1536m
android.useAndroidX=true
org.gradle.java.home=/Users/qdong/Library/Java/JavaVirtualMachines/jbr-17.0.14/Contents/Home
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
