abstract final class AppRoutes {
  static const login = '/login';
  static const signup = '/signup';
  static const signupProfile = '/signup/profile';

  static const topic = '/topic';
  static const topicDetail = 'detail/:tid';
  static const topicSubmit = 'submit';
  static const topicUserSelect = 'user-select';
  static const video = '/video';
  static const videoDetail = 'detail/:videoId';
  static const conversation = '/conversation';
  static const conversationChat = 'chat/:chatId';
  static const conversationRemind = 'remind/:remindType';
  static const conversationFans = 'fans';
  static const me = '/me';
  static const meProfileEdit = '/me/profile-edit';
  static const meTextEdit = '/me/text-edit';
  static const meFriendship = '/me/friendship';
  static const meTopics = '/me/topics';
  static const meNearby = '/me/nearby';
  static const meSearch = '/me/search';
  static const meSearchResult = '/me/search-result';
  static const meSettings = '/me/settings';
  static const mePassword = '/me/password';
  static const meAbout = '/me/about';
  static const meBlacklist = '/me/blacklist';
  static const user = '/user';
  static const userDetail = ':userId';
  static const warningReport = '/report';
}
