import 'package:all_flutter0709/features/conversation/presentation/widgets/chat_input_bar.dart';
import 'package:flutter/material.dart';

/// 草稿表情面板：网格点选后插入输入框。
class ChatEmojiPanel extends StatelessWidget {
  const ChatEmojiPanel({
    super.key,
    required this.height,
    required this.onEmojiTap,
  });

  final double height;
  final ValueChanged<String> onEmojiTap;

  static const List<String> emojiList = [
    '😀',
    '😁',
    '😂',
    '🤣',
    '😃',
    '😄',
    '😅',
    '😆',
    '😉',
    '😊',
    '😋',
    '😎',
    '😍',
    '😘',
    '🥰',
    '😗',
    '😙',
    '😚',
    '🙂',
    '🤗',
    '🤩',
    '🤔',
    '🤨',
    '😐',
    '😑',
    '😶',
    '🙄',
    '😏',
    '😣',
    '😥',
    '😮',
    '🤐',
    '😯',
    '😪',
    '😫',
    '🥱',
    '😴',
    '😌',
    '😛',
    '😜',
    '😝',
    '🤤',
    '😒',
    '😓',
    '😔',
    '😕',
    '🙃',
    '🤑',
    '😲',
    '🙁',
    '😖',
    '😞',
    '😟',
    '😤',
    '😢',
    '😭',
    '😦',
    '😧',
    '😨',
    '😩',
    '🤯',
    '😬',
    '😰',
    '😱',
    '🥵',
    '🥶',
    '😳',
    '🤪',
    '😵',
    '😡',
    '😠',
    '🤬',
    '😷',
    '🤒',
    '🤕',
    '🤢',
    '🤮',
    '🥴',
    '😇',
    '🥳',
    '🥺',
    '🤠',
    '🤡',
    '🤥',
    '🤫',
    '🤭',
    '🧐',
    '🤓',
    '😈',
    '👿',
    '💀',
    '👻',
    '👽',
    '🤖',
    '💩',
    '😺',
    '👍',
    '👎',
    '👏',
    '🙏',
    '💪',
    '🔥',
    '❤️',
    '💔',
    '💕',
    '💯',
    '✨',
    '🎉',
    '🌸',
    '☀️',
    '🌙',
    '⭐',
  ];

  @override
  Widget build(BuildContext context) {
    final bottomPadding = 12 + MediaQuery.paddingOf(context).bottom;
    return ColoredBox(
      color: QInputBarColors.extendBackground,
      child: SizedBox(
        width: double.infinity,
        height: height,
        child: GridView.builder(
          padding: EdgeInsets.fromLTRB(10, 8, 10, bottomPadding),
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
            crossAxisCount: 8,
            mainAxisSpacing: 4,
            crossAxisSpacing: 4,
          ),
          itemCount: emojiList.length,
          itemBuilder: (context, index) {
            final emoji = emojiList[index];
            return GestureDetector(
              behavior: HitTestBehavior.opaque,
              onTap: () => onEmojiTap(emoji),
              child: Center(
                child: Text(emoji, style: const TextStyle(fontSize: 26)),
              ),
            );
          },
        ),
      ),
    );
  }
}
